In [148]:
import pandas as pd

In [149]:
pointers = {
    (-1, -1): "↖",  # NW
    (-1, 1): "↗",  # NE
    (1, 1): "↘",  # SE
    (1, -1): "↙",  # SW
    (0, 1): "→",  # Right
    (1, 0): "↓",  # Down
    (0, -1): "←",  # Left
    (-1, 0): "↑",  # Up
}
directions = tuple(pointers.keys())

In [150]:
# Example matrix and word
matrix = [
    "HGIELSESROHAYCC",
    "HSCARFZHATSOLRD",
    "TAGLOVESINNGLTO",
    "EMISTLETOEDIICE",
    "ETFFERRWEYNTHST",
    "TSORFUFDDRAICNE",
    "GICICLESEASONOS",
    "NRTHTEAHTUTERIC",
    "IHTLIOCISNRZITC",
    "RCAEOISVOAOEMAE",
    "ESLLTINERJNEGTD",
    "TBGCOLDRFOORTIE",
    "TICINESSESMFHPC",
    "AFIREINSMTIIUIE",
    "HSELAGMMOECTECM",
    "CKRARCTICWINDEB",
    "AIETAKSNEDWAIRE",
    "NTERSRAEBRALOPR",
]

In [151]:
df_map = pd.DataFrame([list(m) for m in matrix])
df_map

   0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
0   H  G  I  E  L  S  E  S  R  O  H  A  Y  C  C
1   H  S  C  A  R  F  Z  H  A  T  S  O  L  R  D
2   T  A  G  L  O  V  E  S  I  N  N  G  L  T  O
3   E  M  I  S  T  L  E  T  O  E  D  I  I  C  E
4   E  T  F  F  E  R  R  W  E  Y  N  T  H  S  T
5   T  S  O  R  F  U  F  D  D  R  A  I  C  N  E
6   G  I  C  I  C  L  E  S  E  A  S  O  N  O  S
7   N  R  T  H  T  E  A  H  T  U  T  E  R  I  C
8   I  H  T  L  I  O  C  I  S  N  R  Z  I  T  C
9   R  C  A  E  O  I  S  V  O  A  O  E  M  A  E
10  E  S  L  L  T  I  N  E  R  J  N  E  G  T  D
11  T  B  G  C  O  L  D  R  F  O  O  R  T  I  E
12  T  I  C  I  N  E  S  S  E  S  M  F  H  P  C
13  A  F  I  R  E  I  N  S  M  T  I  I  U  I  E
14  H  S  E  L  A  G  M  M  O  E  C  T  E  C  M
15  C  K  R  A  R  C  T  I  C  W  I  N  D  E  B
16  A  I  E  T  A  K  S  N  E  D  W  A  I  R  E
17  N  T  E  R  S  R  A  E  B  R  A  L  O  P  R

In [152]:
word_list = [
    "ANTIFREEZE",
    "ARCTIC WIND",
    "ASTRONOMIC",
    "BECOME FROSTED",
    "CHATTERING TEETH",
    "CHILLY",
    "CHRISTMAS",
    "COLD",
    "DECEMBER",
    "FIRE",
    "FREEZE",
    "FROST",
    "GALE",
    "GLOVES",
    "HAT",
    "HORSE SLEIGH",
    "ICE",
    "ICICLE",
    "ICINESS",
    "IGLOO",
    "JANUARY",
    "MISTLETOE",
    "POLAR BEARS",
    "PRECIPITATION",
    "SALT",
    "SCARF",
    "SEASON",
    "SHIVER",
    "SKATE",
    "SKI",
    "SNOW",
    "STEW",
]
print(len(word_list))

32

In [153]:
def search_word_in_matrix(matrix: list, word: str) -> list | None:
    """Find word in matrix."""
    rows = len(matrix)
    cols = len(matrix[0])

    def is_valid(x: int, y: int) -> bool:
        return 0 <= x < rows and 0 <= y < cols

    # Function to check if a word exists starting from (i, j) in any direction
    def check_word(i: int, j: int) -> int:
        for nth, direction in enumerate(directions):
            x, y = i, j
            try:
                for k in range(1, len(word)):
                    x += direction[0]
                    y += direction[1]
                    if not is_valid(x, y) or matrix[x][y] != word[k]:
                        raise IndexError  # noqa: TRY301
                return nth  # Found the word  # noqa: TRY300
            except IndexError:
                pass  # Index out of bounds, move to next direction

        return -1

    # Main loop: check each cell in the matrix as the start of the word
    for i in range(rows):
        for j in range(cols):
            if matrix[i][j] == word[0] and (nth := check_word(i, j)) != -1:
                return (i, j, nth, len(word))  # Return the position of the start of the word
    return None  # Word not found


results = []
cnt = 0
for word in word_list:
    result = search_word_in_matrix(matrix, word.replace(" ", ""))
    if result:
        results.append(result)
        print(f"Word {word} found at: {result}" if result else "Word not found", pointers[directions[result[2]]])
    else:
        print(word)
    cnt += 1 if result else 0
print(cnt, len(word_list))

Word ANTIFREEZE found at: (16, 11, 7, 10) ↑
Word ARCTIC WIND found at: (15, 3, 4, 10) →
Word ASTRONOMIC found at: (5, 10, 5, 10) ↓
Word BECOME FROSTED found at: (17, 8, 7, 13) ↑
Word CHATTERING TEETH found at: (15, 0, 7, 15) ↑
Word CHILLY found at: (5, 12, 7, 6) ↑
Word CHRISTMAS found at: (9, 1, 7, 9) ↑
Word COLD found at: (11, 3, 4, 4) →
Word DECEMBER found at: (10, 14, 5, 8) ↓
Word FIRE found at: (13, 1, 4, 4) →
Word FREEZE found at: (5, 6, 7, 6) ↑
Word FROST found at: (5, 4, 6, 5) ←
Word GALE found at: (14, 5, 6, 4) ←
Word GLOVES found at: (2, 2, 4, 6) →
Word HAT found at: (1, 7, 4, 3) →
Word HORSE SLEIGH found at: (0, 10, 6, 11) ←
Word ICE found at: (3, 12, 4, 3) →
Word ICICLE found at: (6, 1, 4, 6) →
Word ICINESS found at: (12, 1, 4, 7) →
Word IGLOO found at: (12, 1, 1, 5) ↗
Word JANUARY found at: (10, 9, 7, 7) ↑
Word MISTLETOE found at: (3, 1, 4, 9) →
Word POLAR BEARS found at: (17, 13, 6, 10) ←
Word PRECIPITATION found at: (17, 13, 7, 13) ↑
Word SALT found at: (10, 1, 1, 4) ↗
Word SCARF found at: (1, 1, 4, 5) →
Word SEASON found at: (6, 7, 4, 6) →
Word SHIVER found at: (6, 7, 5, 6) ↓
Word SKATE found at: (16, 6, 6, 5) ←
Word SKI found at: (14, 1, 5, 3) ↓
Word SNOW found at: (1, 10, 3, 4) ↙
Word STEW found at: (12, 9, 5, 4) ↓
32 32

In [154]:
for x, y, nth, length in results:
    direction = directions[nth]
    for _ in range(length):
        df_map.iloc[x, y] = "*"
        x += direction[0]  # noqa: PLW2901
        y += direction[1]  # noqa: PLW2901

df_map

   0  1  2  3  4  5  6  7  8  9  10 11 12 13 14
0   *  *  *  *  *  *  *  *  *  *  *  A  *  C  C
1   *  *  *  *  *  *  *  *  *  *  *  O  *  R  D
2   *  *  *  *  *  *  *  *  I  *  N  G  *  T  O
3   *  *  *  *  *  *  *  *  *  *  D  I  *  *  *
4   *  *  F  F  E  R  *  *  E  *  N  T  *  S  T
5   *  *  *  *  *  U  *  D  *  *  *  I  *  *  E
6   *  *  *  *  *  *  *  *  *  *  *  *  *  *  S
7   *  *  T  H  *  E  A  *  *  *  *  *  R  *  C
8   *  *  T  *  I  *  C  *  *  *  *  *  I  *  C
9   *  *  *  E  *  I  S  *  *  *  *  *  M  *  E
10  *  *  L  *  T  I  N  *  *  *  *  *  G  *  *
11  *  B  *  *  *  *  *  *  *  O  *  *  T  *  *
12  *  *  *  *  *  *  *  *  *  *  *  *  H  *  *
13  *  *  *  *  *  I  N  S  *  *  *  *  U  *  *
14  *  *  *  *  *  *  M  M  *  *  *  *  E  *  *
15  *  *  R  *  *  *  *  *  *  *  *  *  *  *  *
16  A  *  *  *  *  *  *  N  *  D  W  *  I  *  *
17  N  T  E  R  *  *  *  *  *  *  *  *  *  *  *

In [155]:
ans = []
for i, word in enumerate(word_list):
    result = results[i]
    direction = directions[result[2]]
    print(pointers.get(direction), word, result[0], result[1])
    ans.append((word, pointers.get(direction)))

↑ ANTIFREEZE 16 11
→ ARCTIC WIND 15 3
↓ ASTRONOMIC 5 10
↑ BECOME FROSTED 17 8
↑ CHATTERING TEETH 15 0
↑ CHILLY 5 12
↑ CHRISTMAS 9 1
→ COLD 11 3
↓ DECEMBER 10 14
→ FIRE 13 1
↑ FREEZE 5 6
← FROST 5 4
← GALE 14 5
→ GLOVES 2 2
→ HAT 1 7
← HORSE SLEIGH 0 10
→ ICE 3 12
→ ICICLE 6 1
→ ICINESS 12 1
↗ IGLOO 12 1
↑ JANUARY 10 9
→ MISTLETOE 3 1
← POLAR BEARS 17 13
↑ PRECIPITATION 17 13
↗ SALT 10 1
→ SCARF 1 1
→ SEASON 6 7
↓ SHIVER 6 7
← SKATE 16 6
↓ SKI 14 1
↙ SNOW 1 10
↓ STEW 12 9

In [156]:
df_ans = pd.DataFrame(ans, columns=["word", "direction"])
df_ans.set_index("word", inplace=True)
df_ans["word_length"] = df_ans.index.str.len()
df_ans

                 direction  word_length
word
ANTIFREEZE               ↑           10
ARCTIC WIND              →           11
ASTRONOMIC               ↓           10
BECOME FROSTED           ↑           14
CHATTERING TEETH         ↑           16
CHILLY                   ↑            6
CHRISTMAS                ↑            9
COLD                     →            4
DECEMBER                 ↓            8
FIRE                     →            4
FREEZE                   ↑            6
FROST                    ←            5
GALE                     ←            4
GLOVES                   →            6
HAT                      →            3
HORSE SLEIGH             ←           12
ICE                      →            3
ICICLE                   →            6
ICINESS                  →            7
IGLOO                    ↗            5
JANUARY                  ↑            7
MISTLETOE                →            9
POLAR BEARS              ←           11
PRECIPITATION            ↑           13
SALT                     ↗            4
SCARF                    →            5
SEASON                   →            6
SHIVER                   ↓            6
SKATE                    ←            5
SKI                      ↓            3
SNOW                     ↙            4
STEW                     ↓            4

In [157]:
df_ans.groupby("direction").count().sort_values("word_length")

           word_length
direction
↙                    1
↗                    2
←                    5
↓                    5
↑                    8
→                   11

In [158]:
df_ans = df_ans.reset_index()
df_ans.groupby("direction").agg(
    {
        "word": lambda x: ", ".join(x),  # Concatenate words in each group
        "word_length": "count",  # Count occurrences
    }
)

                                                        word  word_length
direction
←              FROST, GALE, HORSE SLEIGH, POLAR BEARS, SKATE            5
↑          ANTIFREEZE, BECOME FROSTED, CHATTERING TEETH, ...            8
→          ARCTIC WIND, COLD, FIRE, GLOVES, HAT, ICE, ICI...           11
↓                    ASTRONOMIC, DECEMBER, SHIVER, SKI, STEW            5
↗                                                IGLOO, SALT            2
↙                                                       SNOW            1

In [159]:
df_ans = df_ans.reset_index()
df_ans["group_word"] = df_ans["word"]
df_grouped = (
    df_ans.groupby("word_length").agg({"group_word": lambda x: ", ".join(x), "word": "count"})
    # .reset_index()
)
df_grouped

                                                 group_word  word
word_length
3                                             HAT, ICE, SKI     3
4                        COLD, FIRE, GALE, SALT, SNOW, STEW     6
5                                FROST, IGLOO, SCARF, SKATE     4
6            CHILLY, FREEZE, GLOVES, ICICLE, SEASON, SHIVER     6
7                                          ICINESS, JANUARY     2
8                                                  DECEMBER     1
9                                      CHRISTMAS, MISTLETOE     2
10                                   ANTIFREEZE, ASTRONOMIC     2
11                                 ARCTIC WIND, POLAR BEARS     2
12                                             HORSE SLEIGH     1
13                                            PRECIPITATION     1
14                                           BECOME FROSTED     1
16                                         CHATTERING TEETH     1